name: Build and Release Edgeble linux-6.1

on:
  push:
    branches:
      - master

jobs:
  build:
    permissions: write-all
    name: Edgeble linux-6.1 runner
    runs-on: self-hosted
    env:
      OS_VERSION: "v2.04"

    steps:
    - name: Clean runner workspace
      run: |
        sudo rm -rfv ${{ github.workspace }}/*

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Clone linux
      run: git clone git@gitlab.edgeble.ai:core/kernel-6.1.git

    - name: Copy runner.config
      run: cp .github/workflows/runner.config kernel-6.1/arch/arm64/configs/runner.config

    - name: Compile
      run: |
        cd kernel-6.1
        export CROSS_COMPILE=aarch64-linux-gnu-
        ARCH=arm64 make rockchip_linux_defconfig gpu.config edgeble-6tops.config runner.config
        mkdir -p ${{ github.workspace }}/out
        mkdir -p ${{ github.workspace }}/out/linux-6.1
        mkdir -p ${{ github.workspace }}/out/dtb/rockchip
        mkdir -p ${{ github.workspace }}/out/modules-6.1
        ARCH=arm64 make dtbs Image -j 16; ARCH=arm64 make modules -j 16; ARCH=arm64 make modules_install INSTALL_MOD_PATH=${{ github.workspace }}/out

    - name: Copy deb files and create archive
      run: |
        echo "Copy DTB:"
        cp -fv ${{ github.workspace }}/kernel-6.1/arch/arm64/boot/dts/rockchip/rk3588-edgeble-*.dtb ${{ github.workspace }}/out/dtb/rockchip
        cp -fv ${{ github.workspace }}/kernel-6.1/arch/arm64/boot/dts/rockchip/rk3588-edgeble-*.dtbo ${{ github.workspace }}/out/dtb/rockchip
        cp -fv ${{ github.workspace }}/kernel-6.1/arch/arm64/boot/dts/rockchip/rk3588-rock-5b.dtb ${{ github.workspace }}/out/dtb/rockchip
        cp -fv ${{ github.workspace }}/kernel-6.1/arch/arm64/boot/dts/rockchip/rk3588-rock-5b-radxa-camera-4k.dtbo ${{ github.workspace }}/out/dtb/rockchip
        cp -fv ${{ github.workspace }}/kernel-6.1/arch/arm64/boot/dts/rockchip/rk3588-firefly-itx*.dtb ${{ github.workspace }}/out/dtb/rockchip

        echo "Copy config:"
        cp -fv ${{ github.workspace }}/kernel-6.1/.config ${{ github.workspace }}/out/linux-6.1

        echo "Create linux-6.1:"
        cp -frv ${{ github.workspace }}/kernel-6.1/arch/arm64/boot/Image ${{ github.workspace }}/out/dtb ${{ github.workspace }}/out/linux-6.1

        echo "Create modules-6.1:"
        cp -frv ${{ github.workspace }}/out/lib/modules/* ${{ github.workspace }}/out/modules-6.1

        echo "Create tar.xz"
        cd ${{ github.workspace }}/out/
        tar -Jcf linux-6.1.tar.xz linux-6.1 && tar -Jcf modules-6.1.tar.xz modules-6.1

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: "${{ env.OS_VERSION }}"
        body: |
          - Add tower-light
          - Add IMX415 RPi Wave
          - Add Radxa IMX415
        files: |
          ${{ github.workspace }}/out/linux-6.1.tar.xz
          ${{ github.workspace }}/out/modules-6.1.tar.xz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Send email notification on build result
      if: always()  # ensures email gets sent on success or failure
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.SMTP_USERNAME }}
        password: ${{ secrets.SMTP_PASSWORD }}
        subject: |
          [Edgeble linux-6.1.43 ${{ env.OS_VERSION }} Build] ${{ job.status }} â€“ ${{ github.workflow }} @ ${{ github.run_number }}
        body: |
          GitHub Action: ${{ github.workflow }}
          Release: https://github.com/${{ github.repository }}/releases/tag/${{ env.OS_VERSION }}
          Run Number: ${{ github.run_number }}
          Status: ${{ job.status }}
          Commit: ${{ github.sha }}
          Repo: ${{ github.repository }}
          Triggered by: ${{ github.actor }}
          Run: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

        from: ${{ secrets.EMAIL_FROM }}
        bcc: ${{ secrets.EMAIL_TO }}
        secure: false
